# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZfTL8rjgY0ctcyyr_Dtn_3Kq672q-__v
"""

# =============================================================================
# PROYECTO: MANTENIMIENTO PREDICTIVO IoT - RASPBERRY PI PICO (CORE 0 & 1)
# =============================================================================
import machine
import time
import ustruct
import math
import _thread
import gc

# --- CONFIGURACIÓN DE HARDWARE ---
i2c = machine.I2C(0, scl=machine.Pin(1), sda=machine.Pin(0))
sensor_adc = machine.ADC(26)
pin_pasos = machine.Pin(15, machine.Pin.OUT)
pin_boton = machine.Pin(14, machine.Pin.IN, machine.Pin.PULL_DOWN)

# --- PARÁMETROS DE INGENIERÍA ---
LIMITE_CORRIENTE   = 0.70    # Límite máximo de amperaje permitido
LIMITE_VIBRACION   = 1.15    # Límite máximo de vibración (g)
TIEMPO_PARADA_AMP  = 3000    # Falla de corriente (ms)
TIEMPO_PARADA_VIB  = 10000   # Falla de vibración (ms)
ALPHA              = 0.35    # Factor de suavizado (filtro)
TIEMPO_REBOTE_MS   = 300     # Anti-rebote botón

# --- ESTADO GLOBAL ---
sistema_habilitado = True
estado_sistema = "OK"
inicio_falla_amp = 0
inicio_falla_vib = 0
vibracion_suavizada = 0.0
ultimo_cambio_boton = 0
boton_prev = 0
buffer_corr = []
buffer_vib = []
contador = 0

# --- DRIVER MPU6050 ---
class MPU6050:
    def __init__(self, i2c, addr=0x68):
        self.i2c = i2c
        self.addr = addr
        try:
            self.i2c.writeto_mem(self.addr, 0x6B, b'\x00')
        except: pass

    def leer(self):
        try:
            data = self.i2c.readfrom_mem(self.addr, 0x3B, 6)
            ax, ay, az = ustruct.unpack('>hhh', data)
            return math.sqrt((ax/16384.0)**2 + (ay/16384.0)**2 + (az/16384.0)**2)
        except: return None

# --- CALIBRACIÓN INICIAL ---
try:
    mpu = MPU6050(i2c)
except:
    mpu = None

suma = 0
for _ in range(20):
    suma += sensor_adc.read_u16()
    time.sleep_ms(5)
cero_ref_adc = suma / 20
factor_adc = 3.3 / 65535

# --- CORE 1: CONTROL DE MOTOR ---
def tarea_motor():
    global sistema_habilitado
    RETARDO_PASO_US = 1000
    while True:
        if sistema_habilitado:
            pin_pasos.toggle()
            time.sleep_us(RETARDO_PASO_US)
        else:
            time.sleep_ms(20)

_thread.start_new_thread(tarea_motor, ())

# --- CORE 0: BUCLE PRINCIPAL (SENSORES Y LÓGICA) ---
wdt = machine.WDT(timeout=5000)
ultimo_envio = time.ticks_ms()
TIEMPO_MUESTREO = 10

while True:
    wdt.feed()
    ahora_ms = time.ticks_ms()

    # LÓGICA BOTÓN (STOP/REARME)
    boton_act = pin_boton.value()
    if boton_act == 1 and boton_prev == 0:
        if time.ticks_diff(ahora_ms, ultimo_cambio_boton) > TIEMPO_REBOTE_MS:
            try:
                if sistema_habilitado:
                    sistema_habilitado = False
                    estado_sistema = "STOP_MANUAL"
                    print("0.00,0.00,STOP_MANUAL")
                else:
                    inicio_falla_amp = inicio_falla_vib = 0
                    vibracion_suavizada = 0.0
                    buffer_corr = []; buffer_vib = []
                    contador = 0
                    sistema_habilitado = True
                    estado_sistema = "OK"
                    print("0.00,0.00,RESET")
            except: pass
            ultimo_cambio_boton = ahora_ms
    boton_prev = boton_act

    # RECOLECCIÓN DE MUESTRAS
    if time.ticks_diff(ahora_ms, ultimo_envio) >= TIEMPO_MUESTREO:
        if contador == 0: gc.collect()

        # Lectura Corriente
        try:
            adc_val = sensor_adc.read_u16()
            voltaje = (adc_val * factor_adc) - (cero_ref_adc * factor_adc)
            corriente = abs(voltaje / 0.066)
            if corriente < 0.08: corriente = 0.0
        except: corriente = 0.0

        # Lectura Vibración
        vib_raw = None
        if mpu: vib_raw = mpu.leer()
        if vib_raw is None:
            try: mpu = MPU6050(i2c); vib_raw = mpu.leer()
            except: vib_raw = 0.0

        if vib_raw is not None:
            vibracion_suavizada = (vibracion_suavizada * (1 - ALPHA)) + (vib_raw * ALPHA)

        buffer_corr.append(corriente)
        buffer_vib.append(vibracion_suavizada)
        contador += 1

        # PROCESAMIENTO Y ENVÍO (Cada 100ms)
        if contador >= 10:
            prom_corr = sum(buffer_corr) / len(buffer_corr)
            prom_vib = sum(buffer_vib) / len(buffer_vib)

            if estado_sistema != "STOP_MANUAL":
                nuevo_estado = "OK"

                # Lógica Corriente
                if prom_corr > LIMITE_CORRIENTE:
                    if inicio_falla_amp == 0: inicio_falla_amp = ahora_ms
                    if time.ticks_diff(ahora_ms, inicio_falla_amp) > TIEMPO_PARADA_AMP:
                        sistema_habilitado = False
                        nuevo_estado = "STOP_SOBRECORRIENTE"
                    else: nuevo_estado = "ALERTA_CORRIENTE_ALTA"
                else: inicio_falla_amp = 0

                # Lógica Vibración
                if "STOP" not in nuevo_estado:
                    if prom_vib > LIMITE_VIBRACION:
                        if inicio_falla_vib == 0: inicio_falla_vib = ahora_ms
                        if time.ticks_diff(ahora_ms, inicio_falla_vib) > TIEMPO_PARADA_VIB:
                            sistema_habilitado = False
                            nuevo_estado = "STOP_DESBALANCE_MECANICO"
                        else:
                            nuevo_estado = "ALERTA_VIBRACION_EXCESIVA" if nuevo_estado == "OK" else "ALERTA_CRITICA_MULTIPLE"
                    else: inicio_falla_vib = 0

                estado_sistema = nuevo_estado

            print("{:.2f},{:.2f},{}".format(prom_corr, prom_vib, estado_sistema))
            buffer_corr = []; buffer_vib = []; contador = 0

        ultimo_envio = ahora_ms