# -*- coding: utf-8 -*-
"""PROYECTO_FINAL_SENSOR_CORRIENTE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10enQ5xTtlqa3bIexIwLNRoRO3yEUD6WT
"""

# =============================================================================
# UNIVERSIDAD TECNOLÓGICA DEL PERÚ (UTP)
# PROYECTO: SISTEMA DE MANTENIMIENTO PREDICTIVO - GRUPO 1
# =============================================================================

# =============================================================================
# ██████████  BLOQUE 1: CONFIGURACIÓN Y ADQUISICIÓN DE DATOS  ██████████
# RESPONSABLE: INTEGRANTE 1
# TEMAS: Librerías, Variables Globales, Conexión a Dweet.cc
# =============================================================================

import time     # Librería para controlar pausas y tiempos
import requests # Librería para conectarse a internet
import numpy as np  # Librería para matemáticas avanzadas y arrays
import matplotlib.pyplot as plt # Librería para crear los gráficos
from IPython.display import clear_output, display # Para actualizar el gráfico sin parpadear

# --- CONFIGURACIÓN GLOBAL ---
MI_DISPOSITIVO = "proy_final_utp_funciona_v1" # Nombre del script
URL_API = f"https://dweet.cc/get/latest/dweet/for/{MI_DISPOSITIVO}" # Dirección web de donde se guardan los datos
HEADERS = {'User-Agent': 'Mozilla/5.0'} # Nos identificamos como un navegador para que no nos bloqueen

# Parámetros (Límites de seguridad)
LIMITE_VIBRACION = 1.15 # Si pasa de esto, es peligroso (Línea Roja en gráfico)
LIMITE_CORRIENTE = 0.70 # Si pasa de esto, el motor sufre (Línea Naranja en gráfico)
MAX_DATOS = 60          # Cantidad de puntos que se ven en la pantalla (el ancho del gráfico)
FS_ESTIMADA = 20        # Velocidad estimada de datos (para calcular la frecuencia FFT)

# Buffers (Listas de memoria)
# Creamos listas llenas de ceros para empezar con la gráfica vacía
historial_vibracion = [0.0] * MAX_DATOS
historial_corriente = [0.0] * MAX_DATOS

# --- FUNCIONES ---

def obtener_datos_estable():
    """ Descarga los datos de la nube de forma segura """
    try:
        # Intenta conectarse a Dweet con un tiempo máximo de espera de 2 segundos
        respuesta = requests.get(URL_API, headers=HEADERS, timeout=2.0)

        # Si la conexión fue exitosa (Código 200 significa OK)
        if respuesta.status_code == 200:
            datos = respuesta.json() # Convertimos la respuesta de texto a unidades por bloques, como una estructura

            # Verificamos si realmente llegaron datos dentro del paquete
            if "with" in datos and len(datos["with"]) > 0:
                contenido = datos["with"][0]["content"] # Sacamos el contenido útil

                # Extraemos y devolvemos los 3 valores clave, poniendo 0.0 si falta alguno
                return (float(contenido.get("amp", 0.0)),
                        float(contenido.get("vib", 0.0)),
                        contenido.get("status", "DESCONECTADO"))
    except:
        pass # Si falla el internet, no hacemos nada (evitamos que el programa se cierre)
    return None, None, None # Si algo falló, devolvemos "vacío"


# =============================================================================
# ██████████  BLOQUE 2: PROCESAMIENTO DE DATOS Y MATEMÁTICA  ██████████
# RESPONSABLE: INTEGRANTE 2
# TEMAS: Ventana Deslizante (FIFO), Arrays Numpy, Transformada de Fourier
# =============================================================================

def procesar_datos(nuevo_amp, nueva_vib):
    """ Guarda el dato nuevo y borra el más viejo (Cola FIFO) """
    historial_corriente.append(nuevo_amp)   # Agrega la corriente nueva al final de la lista
    historial_vibracion.append(nueva_vib)   # Agrega la vibración nueva al final de la lista

    # Si la lista creció más de lo permitido (60 datos)
    if len(historial_corriente) > MAX_DATOS:
        historial_corriente.pop(0) # Borramos el dato más antiguo (el primero)
        historial_vibracion.pop(0) # Borramos el dato más antiguo de vibración

    # Devolvemos las listas convertidas a Arrays de Numpy para poder graficarlas rápido
    return np.array(historial_corriente), np.array(historial_vibracion)

def calcular_fft_corregida(arr_vib, fs):
    """ Calcula las frecuencias de la vibración (Matemática compleja) """
    n = len(arr_vib) # Contamos cuántos datos tenemos

    # Si hay muy pocos datos o todo es cero, no calculamos nada
    if n < 10 or np.max(arr_vib) == 0:
        return np.linspace(0, 10, 10), np.zeros(10)

    ventana = np.hanning(n) # Filtro suavizado para evitar errores de borde
    espectro = np.fft.fft(arr_vib * ventana) # Aplicamos la Transformada Rápida de Fourier
    freqs = np.fft.fftfreq(n, d=1/fs) # Calculamos el eje X (Hertz)
    mag = (np.abs(espectro) / n) * 2  # Calculamos la altura de las barras (Magnitud real)

    mitad = n // 2 # Solo nos sirve la mitad positiva del espectro
    return freqs[:mitad], mag[:mitad] # Devolvemos frecuencia y magnitud


# =============================================================================
# ██████████  BLOQUE 3: MOTOR GRÁFICO (ARQUITECTURA)  ██████████
# RESPONSABLE: INTEGRANTE 3
# TEMAS: Inicialización, Diseño Estático, Ejes, Creación de Objetos
# =============================================================================

def inicializar_dashboard():
    """ Dibuja el fondo, títulos y ejes UNA SOLA VEZ al principio """
    plt.style.use('dark_background') # Ponemos tema oscuro estilo hacker
    fig = plt.figure(figsize=(12, 10), facecolor='black') # Creamos el lienzo negro
    # Ajustamos márgenes para que todo quepa bien
    plt.subplots_adjust(top=0.77, bottom=0.20, hspace=0.45, wspace=0.3)

    # --- Títulos Estáticos (No cambian) ---
    fig.text(0.5, 0.95, "PANEL DE MANTENIMIENTO PREDICTIVO - GRUPO 1", ha='center', fontsize=24, color='cyan', weight='bold')
    fig.text(0.5, 0.90, "ANÁLISIS DE CAUSA RAÍZ Y DIAGNÓSTICO", ha='center', fontsize=14, color='white')
    fig.text(0.5, 0.80, "Monitor de Tendencia en Tiempo Real", ha='center', fontsize=12, color='gray')

    # --- Objetos Dinámicos (Textos que cambiarán) ---
    # Creamos el cuadro del KPI vacío por ahora
    ref_kpi = fig.text(0.5, 0.85, "CONECTANDO...", ha='center', fontsize=16, color='white',
                       bbox=dict(facecolor='#222', edgecolor='white', boxstyle='round'))

    # Creamos los espacios para los mensajes de alerta (Estado, Causa, Acción)
    ref_icono = fig.text(0.5, 0.14, "", ha='center', fontsize=20, weight='bold')
    ref_causa = fig.text(0.5, 0.09, "", ha='center', fontsize=14, color='yellow')
    ref_accion = fig.text(0.5, 0.04, "", ha='center', fontsize=13, color='white', weight='bold')

    # --- GRÁFICO 1: Líneas (Arriba) ---
    ax1 = plt.subplot(2, 1, 1) # Ubicación: Fila 1, todo el ancho
    ax1.set_facecolor('black') # Fondo negro
    ax1.set_xlim(0, MAX_DATOS) # Eje X fijo de 0 a 60

    # Línea de Vibración (Turquesa)
    linea_vib, = ax1.plot(np.zeros(MAX_DATOS), color='#00ffcc', label='Vibración (g)', lw=2)
    ax1.set_ylabel("Vibración (g)", color='#00ffcc') # Etiqueta Y
    ax1.set_ylim(0, 2.0) # Escala fija de 0 a 2g
    ax1.axhline(LIMITE_VIBRACION, color='red', linestyle='--', alpha=0.5) # Línea punteada de límite
    ax1.legend(loc='upper left') # Leyenda
    ax1.grid(True, alpha=0.15) # Cuadrícula suave

    # Línea de Corriente (Naranja - Eje Gemelo)
    ax1_twin = ax1.twinx() # Creamos un segundo eje Y sobre el mismo gráfico
    linea_corr, = ax1_twin.plot(np.zeros(MAX_DATOS), color='#ffaa00', label='Corriente (A)', ls='--', lw=2)
    ax1_twin.set_ylabel("Corriente (A)", color='#ffaa00')
    ax1_twin.set_ylim(0, 1.5) # Escala fija de 0 a 1.5A
    ax1_twin.axhline(LIMITE_CORRIENTE, color='orange', linestyle='--', alpha=0.5) # Línea punteada límite
    ax1_twin.legend(loc='upper right')

    # --- GRÁFICO 2: FFT (Abajo Izquierda) ---
    ax2 = plt.subplot(2, 2, 3) # Ubicación: Fila 2, Columna 1
    ax2.set_facecolor('black')
    ax2.set_title("Espectro de Frecuencia (FFT)", color='white')
    ax2.set_xlabel("Hz"); ax2.set_ylabel("Mag"); ax2.set_ylim(0, 1.0)
    # Dibujamos barras iniciales vacías
    ax2.bar(np.arange(10), np.zeros(10), color='#bf00ff', alpha=0.9)

    # --- GRÁFICO 3: Scatter (Abajo Derecha) ---
    ax3 = plt.subplot(2, 2, 4) # Ubicación: Fila 2, Columna 2
    ax3.set_facecolor('black')
    ax3.set_title("Matriz Carga vs Vibración", color='white')
    ax3.set_xlabel("Amperios"); ax3.set_ylabel("Vibración g")
    ax3.set_xlim(0, 1.0); ax3.set_ylim(0, 2.0)
    # Zonas de peligro pintadas de rojo y naranja suave
    ax3.axhspan(LIMITE_VIBRACION, 2.0, color='red', alpha=0.1)
    ax3.axvspan(LIMITE_CORRIENTE, 1.0, color='orange', alpha=0.1)

    # Guardamos todas las partes del gráfico en un diccionario para usarlas luego
    referencias = {
        'fig': fig, 'kpi': ref_kpi, 'ico': ref_icono, 'cau': ref_causa, 'acc': ref_accion,
        'l_vib': linea_vib, 'l_cor': linea_corr, 'ax2': ax2, 'ax3': ax3
    }
    return referencias


# =============================================================================
# ██████████  BLOQUE 4: LÓGICA DE CONTROL, ACTUALIZACIÓN Y BUCLE  ██████████
# RESPONSABLE: INTEGRANTE 4
# TEMAS: Lógica del Semáforo, Actualización de Punteros, Ejecución Continua
# =============================================================================

def actualizar_dashboard(refs, arr_a, arr_v, val_a, val_v, estado):
    """ Actualiza SOLO los datos, colores y textos """

    # 1. Actualizar números del KPI central
    refs['kpi'].set_text(f"VIB: {val_v:.2f} g  |  AMP: {val_a:.2f} A")
    # --- SEMÁFORO DE COLORES ---
    # Definimos estado "Normal" por defecto (Negro y Verde)
    bg, txt, ico, msj, cau, acc = "black", "#00ff00", "✅", "NORMAL", "Estable", "Monitoreo activo"

    # Si hay PARADA MANUAL (Prioridad Morada)
    if "MANUAL" in estado:
        bg, txt, ico = "#220022", "magenta", "🖐️"
        msj = "PARADA MANUAL"
        cau, acc = "Operador Local (Pulsador)", "Verificar antes de reiniciar"

    # Si hay STOP DE EMERGENCIA (Prioridad Roja)
    elif "STOP" in estado:
        bg, txt, ico = "#330000", "#ff3333", "⛔"
        msj = "PARADA DE EMERGENCIA"
        # Determinamos si fue por Corriente o Vibración para dar el mensaje correcto
        if "AMP" in estado or "SOBRECORRIENTE" in estado:
            cau, acc = f"Sobrecarga detectada ({val_a} A)", "REVISAR OBSTRUCCIÓN MECÁNICA"
        else:
            cau, acc = f"Desbalance Crítico ({val_v} g)", "REVISAR RODAMIENTOS / EJE"

    # Si hay ALERTA PREVENTIVA (Prioridad Naranja)
    elif "ALERTA" in estado:
        bg, txt, ico = "#442200", "orange", "⚠️"
        msj = "ALERTA TÉCNICA"
        cau, acc = "Umbrales excedidos", "Programar mantenimiento preventivo"

    # Si hay RESET (Prioridad Verde)
    elif "RESET" in estado:
        bg, txt, ico = "black", "#00ff00", "🔄"
        msj = "SISTEMA REARMADO / EN MARCHA"
        cau, acc = "Reset por Operador", "Retomando monitoreo..."

    # Aplicamos los colores y textos calculados al gráfico
    refs['fig'].set_facecolor(bg) # Cambia color de fondo
    refs['ico'].set_text(f"{ico} {msj}"); refs['ico'].set_color(txt)
    refs['ico'].set_bbox(dict(facecolor='black', edgecolor=txt, boxstyle='round,pad=0.5'))
    refs['cau'].set_text(cau)
    refs['acc'].set_text(acc)

    # 2. Actualizar las Líneas del gráfico principal
    x_data = range(len(arr_v)) # Creamos eje X de 0 a 60
    refs['l_vib'].set_data(x_data, arr_v) # Actualizamos línea vibración
    refs['l_cor'].set_data(x_data, arr_a) # Actualizamos línea corriente

    # 3. Actualizar Gráfico FFT
    f, m = calcular_fft_corregida(arr_v, FS_ESTIMADA) # Calculamos matemática nueva
    refs['ax2'].cla() # Limpiamos barras viejas
    refs['ax2'].set_title("Espectro de Frecuencia (FFT)", color='white')
    # Ajustamos altura del eje Y dinámicamente
    ymax = max(0.5, np.max(m)*1.2) if len(m)>0 else 0.5
    refs['ax2'].set_ylim(0, ymax)
    # Dibujamos barras nuevas en MORADO
    refs['ax2'].bar(f, m, width=0.5, color='#bf00ff', alpha=0.9)
    refs['ax2'].grid(True, alpha=0.2)

    # 4. Actualizar Gráfico de Dispersión
    refs['ax3'].cla() # Limpiamos puntos viejos
    refs['ax3'].set_title("Matriz Carga vs Vibración", color='white')
    refs['ax3'].set_xlim(0, 1.0); refs['ax3'].set_ylim(0, 2.0)
    # Repintamos las zonas de peligro
    refs['ax3'].axhspan(LIMITE_VIBRACION, 2.0, color='red', alpha=0.1)
    refs['ax3'].axvspan(LIMITE_CORRIENTE, 1.0, color='orange', alpha=0.1)

    # Calculamos color de cada punto (Rojo si peligro, Verde si bien)
    colores = ['red' if (v > LIMITE_VIBRACION or a > LIMITE_CORRIENTE) else 'lime' for a, v in zip(arr_a, arr_v)]
    refs['ax3'].scatter(arr_a, arr_v, c=colores, s=40) # Dibujamos puntos
    refs['ax3'].set_xlabel("Amperios"); refs['ax3'].set_ylabel("Vibración g")
    refs['ax3'].grid(True, alpha=0.2)

    return refs['fig'] # Devolvemos la figura actualizada

# --- BUCLE PRINCIPAL (DONDE TODO EMPIEZA) ---
print("Iniciando Dashboard Final (Rearme sin borrado)...")

# 1. Creamos el tablero una sola vez antes de empezar
referencias = inicializar_dashboard()
handle = display(referencias['fig'], display_id='tablero_final_rearme') # Lo mostramos en pantalla

try:
    while True: # Bucle infinito (corre para siempre)
        # Bajamos datos de internet
        d_amp, d_vib, d_estado = obtener_datos_estable()

        if d_amp is not None: # Si llegaron datos válidos...
            # Procesamos y guardamos en historial
            arr_a, arr_v = procesar_datos(d_amp, d_vib)

            # Actualizamos los dibujos en pantalla
            actualizar_dashboard(referencias, arr_a, arr_v, d_amp, d_vib, d_estado)

            # Refrescamos la imagen
            handle.update(referencias['fig'])

            # Esperamos 0.5 segundos para no saturar la red (Estabilidad)
            time.sleep(0.5)
        else:
            # Si falló internet, esperamos igual
            time.sleep(0.5)

except KeyboardInterrupt: # Si presionamos stop en el teclado
    print("Sistema detenido.")
    plt.close('all') # Cierra todas las ventanas gráficas